# Generated by Django 4.2.7 on 2025-07-27 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.CharField(blank=True, help_text='Image URL or emoji', max_length=500, null=True),
        ),
    ]
