# Generated by Django 4.2.7 on 2025-07-27 18:16

from django.db import migrations, models
import posts.models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_alter_post_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='emoji',
            field=models.CharField(blank=True, help_text='Optional emoji or short text', max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=posts.models.post_image_upload_path),
        ),
    ]
